
var request = require('superagent');

var Lookup = module.exports = function (apiKey) {
  this.endpoint =
    'https://api.forecast.io/forecast/';
  this.apiKey = apiKey;
};

Lookup.prototype.getWeather = function (latitude, longitude, callback) {
  if (!longitude || !latitude) {
    return callback(new Error('Missing longitude/lattitude data'));
  }

  var requestData = '/' + latitude + ',' + longitude;

  request
    .get(this.endpoint + this.apiKey + requestData)
    .set('Accept', 'application/json')
    .end(function (err, res) {
      if (err) {
        return callback(err);
      }

      var data = res.body || {};

      if (!data.currently) {
        return callback(new Error('Invalid response from weather api'));
      }

      return callback(undefined, data);
    });
};

/*
{
    "latitude": 37.8267,
    "longitude": -122.423,
    "timezone": "America/Los_Angeles",
    "offset": -8,
    "currently": {
        "time": 1391914871,
        "summary": "Drizzle",
        "icon": "rain",
        "nearestStormDistance": 0,
        "precipIntensity": 0.0056,
        "precipIntensityError": 0.0005,
        "precipProbability": 1,
        "precipType": "rain",
        "temperature": 57.28,
        "apparentTemperature": 57.28,
        "dewPoint": 55.98,
        "humidity": 0.95,
        "windSpeed": 11.27,
        "windBearing": 205,
        "visibility": 4.33,
        "cloudCover": 1,
        "pressure": 1019.63,
        "ozone": 290.53
    },
    "minutely": {
        "summary": "Drizzle for 35 min.",
        "icon": "rain",
        "data": [
            {
                "time": 1391914860,
                "precipIntensity": 0.0056,
                "precipIntensityError": 0.0005,
                "precipProbability": 1,
                "precipType": "rain"
            },
            {
                "time": 1391914920,
                "precipIntensity": 0.0057,
                "precipIntensityError": 0.0007,
                "precipProbability": 1,
                "precipType": "rain"
            },
            {
                "time": 1391914980,
                "precipIntensity": 0.0065,
                "precipIntensityError": 0.0011,
                "precipProbability": 0.99,
                "precipType": "rain"
            },
            {
                "time": 1391915040,
                "precipIntensity": 0.0069,
                "precipIntensityError": 0.0012,
                "precipProbability": 1,
                "precipType": "rain"
            },
            {
                "time": 1391915100,
                "precipIntensity": 0.0071,
                "precipIntensityError": 0.0014,
                "precipProbability": 0.99,
                "precipType": "rain"
            },
            {
                "time": 1391915160,
                "precipIntensity": 0.0073,
                "precipIntensityError": 0.0014,
                "precipProbability": 0.98,
                "precipType": "rain"
            },
            {
                "time": 1391915220,
                "precipIntensity": 0.0076,
                "precipIntensityError": 0.0015,
                "precipProbability": 0.98,
                "precipType": "rain"
            },
            {
                "time": 1391915280,
                "precipIntensity": 0.0076,
                "precipIntensityError": 0.0015,
                "precipProbability": 0.97,
                "precipType": "rain"
            },
            {
                "time": 1391915340,
                "precipIntensity": 0.0075,
                "precipIntensityError": 0.0015,
                "precipProbability": 0.96,
                "precipType": "rain"
            },
            {
                "time": 1391915400,
                "precipIntensity": 0.007,
                "precipIntensityError": 0.0015,
                "precipProbability": 0.95,
                "precipType": "rain"
            },
            {
                "time": 1391915460,
                "precipIntensity": 0.0067,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.93,
                "precipType": "rain"
            },
            {
                "time": 1391915520,
                "precipIntensity": 0.0065,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.92,
                "precipType": "rain"
            },
            {
                "time": 1391915580,
                "precipIntensity": 0.0061,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.9,
                "precipType": "rain"
            },
            {
                "time": 1391915640,
                "precipIntensity": 0.006,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.88,
                "precipType": "rain"
            },
            {
                "time": 1391915700,
                "precipIntensity": 0.0059,
                "precipIntensityError": 0.0015,
                "precipProbability": 0.86,
                "precipType": "rain"
            },
            {
                "time": 1391915760,
                "precipIntensity": 0.0057,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.84,
                "precipType": "rain"
            },
            {
                "time": 1391915820,
                "precipIntensity": 0.0055,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.8,
                "precipType": "rain"
            },
            {
                "time": 1391915880,
                "precipIntensity": 0.0054,
                "precipIntensityError": 0.0016,
                "precipProbability": 0.78,
                "precipType": "rain"
            },
            {
                "time": 1391915940,
                "precipIntensity": 0.0054,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.75,
                "precipType": "rain"
            },
            {
                "time": 1391916000,
                "precipIntensity": 0.0054,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.73,
                "precipType": "rain"
            },
            {
                "time": 1391916060,
                "precipIntensity": 0.0054,
                "precipIntensityError": 0.002,
                "precipProbability": 0.72,
                "precipType": "rain"
            },
            {
                "time": 1391916120,
                "precipIntensity": 0.0054,
                "precipIntensityError": 0.002,
                "precipProbability": 0.72,
                "precipType": "rain"
            },
            {
                "time": 1391916180,
                "precipIntensity": 0.0055,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.72,
                "precipType": "rain"
            },
            {
                "time": 1391916240,
                "precipIntensity": 0.0056,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.71,
                "precipType": "rain"
            },
            {
                "time": 1391916300,
                "precipIntensity": 0.0056,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.71,
                "precipType": "rain"
            },
            {
                "time": 1391916360,
                "precipIntensity": 0.0056,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.69,
                "precipType": "rain"
            },
            {
                "time": 1391916420,
                "precipIntensity": 0.0055,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.68,
                "precipType": "rain"
            },
            {
                "time": 1391916480,
                "precipIntensity": 0.0055,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.66,
                "precipType": "rain"
            },
            {
                "time": 1391916540,
                "precipIntensity": 0.0054,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.65,
                "precipType": "rain"
            },
            {
                "time": 1391916600,
                "precipIntensity": 0.0053,
                "precipIntensityError": 0.0022,
                "precipProbability": 0.61,
                "precipType": "rain"
            },
            {
                "time": 1391916660,
                "precipIntensity": 0.0052,
                "precipIntensityError": 0.0022,
                "precipProbability": 0.59,
                "precipType": "rain"
            },
            {
                "time": 1391916720,
                "precipIntensity": 0.0051,
                "precipIntensityError": 0.0022,
                "precipProbability": 0.57,
                "precipType": "rain"
            },
            {
                "time": 1391916780,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.54,
                "precipType": "rain"
            },
            {
                "time": 1391916840,
                "precipIntensity": 0.0049,
                "precipIntensityError": 0.0021,
                "precipProbability": 0.52,
                "precipType": "rain"
            },
            {
                "time": 1391916900,
                "precipIntensity": 0.0049,
                "precipIntensityError": 0.002,
                "precipProbability": 0.5,
                "precipType": "rain"
            },
            {
                "time": 1391916960,
                "precipIntensity": 0.0048,
                "precipIntensityError": 0.002,
                "precipProbability": 0.48,
                "precipType": "rain"
            },
            {
                "time": 1391917020,
                "precipIntensity": 0.0047,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.45,
                "precipType": "rain"
            },
            {
                "time": 1391917080,
                "precipIntensity": 0.0047,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.43,
                "precipType": "rain"
            },
            {
                "time": 1391917140,
                "precipIntensity": 0.0046,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.43,
                "precipType": "rain"
            },
            {
                "time": 1391917200,
                "precipIntensity": 0.0045,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.4,
                "precipType": "rain"
            },
            {
                "time": 1391917260,
                "precipIntensity": 0.0045,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.39,
                "precipType": "rain"
            },
            {
                "time": 1391917320,
                "precipIntensity": 0.0045,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.37,
                "precipType": "rain"
            },
            {
                "time": 1391917380,
                "precipIntensity": 0.0044,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.35,
                "precipType": "rain"
            },
            {
                "time": 1391917440,
                "precipIntensity": 0.0044,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.34,
                "precipType": "rain"
            },
            {
                "time": 1391917500,
                "precipIntensity": 0.0044,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.31,
                "precipType": "rain"
            },
            {
                "time": 1391917560,
                "precipIntensity": 0.0044,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.29,
                "precipType": "rain"
            },
            {
                "time": 1391917620,
                "precipIntensity": 0.0044,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.27,
                "precipType": "rain"
            },
            {
                "time": 1391917680,
                "precipIntensity": 0.0043,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.25,
                "precipType": "rain"
            },
            {
                "time": 1391917740,
                "precipIntensity": 0.0042,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.24,
                "precipType": "rain"
            },
            {
                "time": 1391917800,
                "precipIntensity": 0.0041,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.22,
                "precipType": "rain"
            },
            {
                "time": 1391917860,
                "precipIntensity": 0.0041,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.21,
                "precipType": "rain"
            },
            {
                "time": 1391917920,
                "precipIntensity": 0.004,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.18,
                "precipType": "rain"
            },
            {
                "time": 1391917980,
                "precipIntensity": 0.0039,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.18,
                "precipType": "rain"
            },
            {
                "time": 1391918040,
                "precipIntensity": 0.0038,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.16,
                "precipType": "rain"
            },
            {
                "time": 1391918100,
                "precipIntensity": 0.0039,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.14,
                "precipType": "rain"
            },
            {
                "time": 1391918160,
                "precipIntensity": 0.0038,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.13,
                "precipType": "rain"
            },
            {
                "time": 1391918220,
                "precipIntensity": 0.0038,
                "precipIntensityError": 0.0019,
                "precipProbability": 0.12,
                "precipType": "rain"
            },
            {
                "time": 1391918280,
                "precipIntensity": 0.0037,
                "precipIntensityError": 0.0018,
                "precipProbability": 0.11,
                "precipType": "rain"
            },
            {
                "time": 1391918340,
                "precipIntensity": 0.0036,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.1,
                "precipType": "rain"
            },
            {
                "time": 1391918400,
                "precipIntensity": 0.0036,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.1,
                "precipType": "rain"
            },
            {
                "time": 1391918460,
                "precipIntensity": 0.0035,
                "precipIntensityError": 0.0017,
                "precipProbability": 0.09,
                "precipType": "rain"
            }
        ]
    },
    "hourly": {
        "summary": "Breezy starting tonight, continuing until tomorrow evening, with rain later this evening.",
        "icon": "rain",
        "data": [
            {
                "time": 1391914800,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0198,
                "precipProbability": 0.85,
                "precipType": "rain",
                "temperature": 57.27,
                "apparentTemperature": 57.27,
                "dewPoint": 55.98,
                "humidity": 0.95,
                "windSpeed": 11.3,
                "windBearing": 205,
                "visibility": 4.33,
                "cloudCover": 1,
                "pressure": 1019.63,
                "ozone": 290.51
            },
            {
                "time": 1391918400,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.029,
                "precipProbability": 0.84,
                "precipType": "rain",
                "temperature": 57.63,
                "apparentTemperature": 57.63,
                "dewPoint": 56.22,
                "humidity": 0.95,
                "windSpeed": 10.26,
                "windBearing": 204,
                "visibility": 4.23,
                "cloudCover": 1,
                "pressure": 1019.92,
                "ozone": 291.33
            },
            {
                "time": 1391922000,
                "summary": "Rain",
                "icon": "rain",
                "precipIntensity": 0.064,
                "precipProbability": 0.84,
                "precipType": "rain",
                "temperature": 57.36,
                "apparentTemperature": 57.36,
                "dewPoint": 56.07,
                "humidity": 0.95,
                "windSpeed": 11.35,
                "windBearing": 202,
                "visibility": 4.94,
                "cloudCover": 1,
                "pressure": 1020.37,
                "ozone": 292.35
            },
            {
                "time": 1391925600,
                "summary": "Rain",
                "icon": "rain",
                "precipIntensity": 0.0714,
                "precipProbability": 0.86,
                "precipType": "rain",
                "temperature": 56.82,
                "apparentTemperature": 56.82,
                "dewPoint": 55.69,
                "humidity": 0.96,
                "windSpeed": 12.4,
                "windBearing": 203,
                "visibility": 4.74,
                "cloudCover": 1,
                "pressure": 1020.66,
                "ozone": 293.15
            },
            {
                "time": 1391929200,
                "summary": "Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0888,
                "precipProbability": 0.9,
                "precipType": "rain",
                "temperature": 56.42,
                "apparentTemperature": 56.42,
                "dewPoint": 55.18,
                "humidity": 0.96,
                "windSpeed": 12.81,
                "windBearing": 209,
                "visibility": 3.97,
                "cloudCover": 1,
                "pressure": 1020.62,
                "ozone": 293.58
            },
            {
                "time": 1391932800,
                "summary": "Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0696,
                "precipProbability": 0.97,
                "precipType": "rain",
                "temperature": 56.53,
                "apparentTemperature": 56.53,
                "dewPoint": 55.19,
                "humidity": 0.95,
                "windSpeed": 13.23,
                "windBearing": 213,
                "visibility": 4.12,
                "cloudCover": 1,
                "pressure": 1020.41,
                "ozone": 293.79
            },
            {
                "time": 1391936400,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0449,
                "precipProbability": 1,
                "precipType": "rain",
                "temperature": 55.87,
                "apparentTemperature": 55.87,
                "dewPoint": 54.67,
                "humidity": 0.96,
                "windSpeed": 14.34,
                "windBearing": 214,
                "visibility": 4.52,
                "cloudCover": 1,
                "pressure": 1020.28,
                "ozone": 293.8
            },
            {
                "time": 1391940000,
                "summary": "Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0558,
                "precipProbability": 0.95,
                "precipType": "rain",
                "temperature": 55.85,
                "apparentTemperature": 55.85,
                "dewPoint": 54.6,
                "humidity": 0.96,
                "windSpeed": 14.72,
                "windBearing": 214,
                "visibility": 4.72,
                "cloudCover": 1,
                "pressure": 1020.27,
                "ozone": 293.44
            },
            {
                "time": 1391943600,
                "summary": "Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0709,
                "precipProbability": 0.88,
                "precipType": "rain",
                "temperature": 55.45,
                "apparentTemperature": 55.45,
                "dewPoint": 54.28,
                "humidity": 0.96,
                "windSpeed": 14.18,
                "windBearing": 217,
                "visibility": 4.78,
                "cloudCover": 1,
                "pressure": 1020.31,
                "ozone": 292.88
            },
            {
                "time": 1391947200,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0462,
                "precipProbability": 0.84,
                "precipType": "rain",
                "temperature": 55.42,
                "apparentTemperature": 55.42,
                "dewPoint": 54.36,
                "humidity": 0.96,
                "windSpeed": 13.51,
                "windBearing": 218,
                "visibility": 5.56,
                "cloudCover": 1,
                "pressure": 1020.25,
                "ozone": 292.62
            },
            {
                "time": 1391950800,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0272,
                "precipProbability": 0.76,
                "precipType": "rain",
                "temperature": 55.39,
                "apparentTemperature": 55.39,
                "dewPoint": 54.37,
                "humidity": 0.96,
                "windSpeed": 12.39,
                "windBearing": 215,
                "visibility": 4.98,
                "cloudCover": 1,
                "pressure": 1019.98,
                "ozone": 292.85
            },
            {
                "time": 1391954400,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0195,
                "precipProbability": 0.8,
                "precipType": "rain",
                "temperature": 55.37,
                "apparentTemperature": 55.37,
                "dewPoint": 54.14,
                "humidity": 0.96,
                "windSpeed": 11.4,
                "windBearing": 212,
                "visibility": 4.91,
                "cloudCover": 1,
                "pressure": 1019.61,
                "ozone": 293.37
            },
            {
                "time": 1391958000,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0211,
                "precipProbability": 0.97,
                "precipType": "rain",
                "temperature": 55.37,
                "apparentTemperature": 55.37,
                "dewPoint": 54.07,
                "humidity": 0.95,
                "windSpeed": 11.18,
                "windBearing": 211,
                "visibility": 4.83,
                "cloudCover": 1,
                "pressure": 1019.38,
                "ozone": 294.08
            },
            {
                "time": 1391961600,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0381,
                "precipProbability": 1,
                "precipType": "rain",
                "temperature": 55.39,
                "apparentTemperature": 55.39,
                "dewPoint": 54.13,
                "humidity": 0.96,
                "windSpeed": 10.88,
                "windBearing": 208,
                "visibility": 4.69,
                "cloudCover": 1,
                "pressure": 1019.44,
                "ozone": 295.04
            },
            {
                "time": 1391965200,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0518,
                "precipProbability": 1,
                "precipType": "rain",
                "temperature": 55.32,
                "apparentTemperature": 55.32,
                "dewPoint": 54.04,
                "humidity": 0.95,
                "windSpeed": 11.3,
                "windBearing": 203,
                "visibility": 4.35,
                "cloudCover": 1,
                "pressure": 1019.57,
                "ozone": 296.19
            },
            {
                "time": 1391968800,
                "summary": "Rain",
                "icon": "rain",
                "precipIntensity": 0.0738,
                "precipProbability": 0.99,
                "precipType": "rain",
                "temperature": 55.29,
                "apparentTemperature": 55.29,
                "dewPoint": 53.93,
                "humidity": 0.95,
                "windSpeed": 12.11,
                "windBearing": 205,
                "visibility": 4.56,
                "cloudCover": 1,
                "pressure": 1019.6,
                "ozone": 297.23
            },
            {
                "time": 1391972400,
                "summary": "Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0667,
                "precipProbability": 0.95,
                "precipType": "rain",
                "temperature": 55.57,
                "apparentTemperature": 55.57,
                "dewPoint": 53.92,
                "humidity": 0.94,
                "windSpeed": 13.05,
                "windBearing": 207,
                "visibility": 4.65,
                "cloudCover": 1,
                "pressure": 1019.49,
                "ozone": 297.85
            },
            {
                "time": 1391976000,
                "summary": "Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0549,
                "precipProbability": 0.88,
                "precipType": "rain",
                "temperature": 55.79,
                "apparentTemperature": 55.79,
                "dewPoint": 54.06,
                "humidity": 0.94,
                "windSpeed": 14,
                "windBearing": 208,
                "visibility": 6.07,
                "cloudCover": 1,
                "pressure": 1019.31,
                "ozone": 298.38
            },
            {
                "time": 1391979600,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.043,
                "precipProbability": 0.82,
                "precipType": "rain",
                "temperature": 56.11,
                "apparentTemperature": 56.11,
                "dewPoint": 54.22,
                "humidity": 0.93,
                "windSpeed": 14.68,
                "windBearing": 210,
                "visibility": 7.57,
                "cloudCover": 1,
                "pressure": 1019.11,
                "ozone": 299.42
            },
            {
                "time": 1391983200,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0375,
                "precipProbability": 0.81,
                "precipType": "rain",
                "temperature": 56.4,
                "apparentTemperature": 56.4,
                "dewPoint": 54.42,
                "humidity": 0.93,
                "windSpeed": 15.01,
                "windBearing": 215,
                "visibility": 8.5,
                "cloudCover": 1,
                "pressure": 1018.88,
                "ozone": 301.55
            },
            {
                "time": 1391986800,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.035,
                "precipProbability": 0.82,
                "precipType": "rain",
                "temperature": 56.59,
                "apparentTemperature": 56.59,
                "dewPoint": 54.46,
                "humidity": 0.93,
                "windSpeed": 15,
                "windBearing": 220,
                "visibility": 8.87,
                "cloudCover": 1,
                "pressure": 1018.67,
                "ozone": 304.19
            },
            {
                "time": 1391990400,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0312,
                "precipProbability": 0.82,
                "precipType": "rain",
                "temperature": 56.98,
                "apparentTemperature": 56.98,
                "dewPoint": 54.97,
                "humidity": 0.93,
                "windSpeed": 15.09,
                "windBearing": 225,
                "visibility": 9.45,
                "cloudCover": 1,
                "pressure": 1018.54,
                "ozone": 306.26
            },
            {
                "time": 1391994000,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0263,
                "precipProbability": 0.76,
                "precipType": "rain",
                "temperature": 56.83,
                "apparentTemperature": 56.83,
                "dewPoint": 54.93,
                "humidity": 0.93,
                "windSpeed": 13.75,
                "windBearing": 229,
                "visibility": 9.57,
                "cloudCover": 1,
                "pressure": 1018.55,
                "ozone": 307.07
            },
            {
                "time": 1391997600,
                "summary": "Light Rain and Breezy",
                "icon": "rain",
                "precipIntensity": 0.0204,
                "precipProbability": 0.68,
                "precipType": "rain",
                "temperature": 56.63,
                "apparentTemperature": 56.63,
                "dewPoint": 54.98,
                "humidity": 0.94,
                "windSpeed": 12.12,
                "windBearing": 231,
                "visibility": 9.82,
                "cloudCover": 1,
                "pressure": 1018.65,
                "ozone": 307.29
            },
            {
                "time": 1392001200,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0162,
                "precipProbability": 0.66,
                "precipType": "rain",
                "temperature": 56.4,
                "apparentTemperature": 56.4,
                "dewPoint": 55.24,
                "humidity": 0.96,
                "windSpeed": 10.68,
                "windBearing": 232,
                "visibility": 10,
                "cloudCover": 1,
                "pressure": 1018.84,
                "ozone": 307.9
            },
            {
                "time": 1392004800,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0154,
                "precipProbability": 0.73,
                "precipType": "rain",
                "temperature": 56.24,
                "apparentTemperature": 56.24,
                "dewPoint": 55.3,
                "humidity": 0.97,
                "windSpeed": 9.53,
                "windBearing": 233,
                "visibility": 10,
                "cloudCover": 1,
                "pressure": 1019.18,
                "ozone": 309.31
            },
            {
                "time": 1392008400,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0163,
                "precipProbability": 0.85,
                "precipType": "rain",
                "temperature": 56.13,
                "apparentTemperature": 56.13,
                "dewPoint": 55.33,
                "humidity": 0.97,
                "windSpeed": 8.43,
                "windBearing": 234,
                "visibility": 10,
                "cloudCover": 1,
                "pressure": 1019.61,
                "ozone": 311.11
            },
            {
                "time": 1392012000,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.016,
                "precipProbability": 0.88,
                "precipType": "rain",
                "temperature": 56.05,
                "apparentTemperature": 56.05,
                "dewPoint": 55.32,
                "humidity": 0.97,
                "windSpeed": 7.33,
                "windBearing": 235,
                "visibility": 10,
                "cloudCover": 0.99,
                "pressure": 1019.96,
                "ozone": 312.99
            },
            {
                "time": 1392015600,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0132,
                "precipProbability": 0.71,
                "precipType": "rain",
                "temperature": 55.88,
                "apparentTemperature": 55.88,
                "dewPoint": 55.21,
                "humidity": 0.98,
                "windSpeed": 6.31,
                "windBearing": 238,
                "visibility": 10,
                "cloudCover": 0.99,
                "pressure": 1020.11,
                "ozone": 314.66
            },
            {
                "time": 1392019200,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0091,
                "precipProbability": 0.45,
                "precipType": "rain",
                "temperature": 55.72,
                "apparentTemperature": 55.72,
                "dewPoint": 55.09,
                "humidity": 0.98,
                "windSpeed": 5.41,
                "windBearing": 244,
                "visibility": 10,
                "cloudCover": 0.99,
                "pressure": 1020.18,
                "ozone": 316.42
            },
            {
                "time": 1392022800,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0058,
                "precipProbability": 0.24,
                "precipType": "rain",
                "temperature": 55.55,
                "apparentTemperature": 55.55,
                "dewPoint": 54.94,
                "humidity": 0.98,
                "windSpeed": 4.72,
                "windBearing": 252,
                "visibility": 10,
                "cloudCover": 0.98,
                "pressure": 1020.32,
                "ozone": 318.87
            },
            {
                "time": 1392026400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0041,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperature": 55.46,
                "apparentTemperature": 55.46,
                "dewPoint": 54.85,
                "humidity": 0.98,
                "windSpeed": 4.37,
                "windBearing": 262,
                "visibility": 10,
                "cloudCover": 0.98,
                "pressure": 1020.59,
                "ozone": 323.18
            },
            {
                "time": 1392030000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0032,
                "precipProbability": 0.07,
                "precipType": "rain",
                "temperature": 55.39,
                "apparentTemperature": 55.39,
                "dewPoint": 54.77,
                "humidity": 0.98,
                "windSpeed": 4.31,
                "windBearing": 274,
                "visibility": 10,
                "cloudCover": 0.99,
                "pressure": 1020.96,
                "ozone": 328.18
            },
            {
                "time": 1392033600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0025,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperature": 55.23,
                "apparentTemperature": 55.23,
                "dewPoint": 54.58,
                "humidity": 0.98,
                "windSpeed": 4.43,
                "windBearing": 287,
                "visibility": 10,
                "cloudCover": 0.99,
                "pressure": 1021.4,
                "ozone": 331.03
            },
            {
                "time": 1392037200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0019,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 54.85,
                "apparentTemperature": 54.85,
                "dewPoint": 54.18,
                "humidity": 0.98,
                "windSpeed": 4.65,
                "windBearing": 300,
                "visibility": 10,
                "cloudCover": 0.99,
                "pressure": 1021.89,
                "ozone": 329.8
            },
            {
                "time": 1392040800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0014,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 54.37,
                "apparentTemperature": 54.37,
                "dewPoint": 53.66,
                "humidity": 0.97,
                "windSpeed": 4.97,
                "windBearing": 311,
                "visibility": 10,
                "cloudCover": 0.98,
                "pressure": 1022.44,
                "ozone": 326.42
            },
            {
                "time": 1392044400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0011,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 54.11,
                "apparentTemperature": 54.11,
                "dewPoint": 53.18,
                "humidity": 0.97,
                "windSpeed": 5.22,
                "windBearing": 319,
                "visibility": 10,
                "cloudCover": 0.96,
                "pressure": 1023.01,
                "ozone": 323.83
            },
            {
                "time": 1392048000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0009,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 54.22,
                "apparentTemperature": 54.22,
                "dewPoint": 52.79,
                "humidity": 0.95,
                "windSpeed": 5,
                "windBearing": 324,
                "visibility": 10,
                "cloudCover": 0.92,
                "pressure": 1023.64,
                "ozone": 323.19
            },
            {
                "time": 1392051600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.61,
                "apparentTemperature": 54.61,
                "dewPoint": 52.49,
                "humidity": 0.93,
                "windSpeed": 4.61,
                "windBearing": 329,
                "visibility": 10,
                "cloudCover": 0.85,
                "pressure": 1024.25,
                "ozone": 323.35
            },
            {
                "time": 1392055200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.17,
                "apparentTemperature": 55.17,
                "dewPoint": 52.33,
                "humidity": 0.9,
                "windSpeed": 4.41,
                "windBearing": 331,
                "visibility": 10,
                "cloudCover": 0.79,
                "pressure": 1024.62,
                "ozone": 323.72
            },
            {
                "time": 1392058800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.95,
                "apparentTemperature": 55.95,
                "dewPoint": 52.33,
                "humidity": 0.88,
                "windSpeed": 4.43,
                "windBearing": 331,
                "visibility": 10,
                "cloudCover": 0.75,
                "pressure": 1024.62,
                "ozone": 324.11
            },
            {
                "time": 1392062400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.87,
                "apparentTemperature": 56.87,
                "dewPoint": 52.42,
                "humidity": 0.85,
                "windSpeed": 4.85,
                "windBearing": 323,
                "visibility": 10,
                "cloudCover": 0.73,
                "pressure": 1024.41,
                "ozone": 324.73
            },
            {
                "time": 1392066000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 57.59,
                "apparentTemperature": 57.59,
                "dewPoint": 52.46,
                "humidity": 0.83,
                "windSpeed": 5.45,
                "windBearing": 317,
                "visibility": 10,
                "cloudCover": 0.67,
                "pressure": 1024.14,
                "ozone": 325.57
            },
            {
                "time": 1392069600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.1,
                "apparentTemperature": 58.1,
                "dewPoint": 52.45,
                "humidity": 0.81,
                "windSpeed": 6.27,
                "windBearing": 311,
                "visibility": 10,
                "cloudCover": 0.52,
                "pressure": 1023.85,
                "ozone": 327.14
            },
            {
                "time": 1392073200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.41,
                "apparentTemperature": 58.41,
                "dewPoint": 52.42,
                "humidity": 0.8,
                "windSpeed": 7.39,
                "windBearing": 306,
                "visibility": 10,
                "cloudCover": 0.33,
                "pressure": 1023.56,
                "ozone": 328.94
            },
            {
                "time": 1392076800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.24,
                "apparentTemperature": 58.24,
                "dewPoint": 52.33,
                "humidity": 0.81,
                "windSpeed": 7.94,
                "windBearing": 303,
                "visibility": 10,
                "cloudCover": 0.18,
                "pressure": 1023.41,
                "ozone": 329.48
            },
            {
                "time": 1392080400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 57.24,
                "apparentTemperature": 57.24,
                "dewPoint": 52.09,
                "humidity": 0.83,
                "windSpeed": 8.11,
                "windBearing": 302,
                "visibility": 10,
                "cloudCover": 0.13,
                "pressure": 1023.47,
                "ozone": 327.73
            },
            {
                "time": 1392084000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.76,
                "apparentTemperature": 55.76,
                "dewPoint": 51.75,
                "humidity": 0.86,
                "windSpeed": 8.28,
                "windBearing": 304,
                "visibility": 10,
                "cloudCover": 0.12,
                "pressure": 1023.67,
                "ozone": 324.72
            },
            {
                "time": 1392087600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.53,
                "apparentTemperature": 54.53,
                "dewPoint": 51.45,
                "humidity": 0.89,
                "windSpeed": 8.26,
                "windBearing": 305,
                "visibility": 10,
                "cloudCover": 0.15,
                "pressure": 1023.87,
                "ozone": 322.04
            }
        ]
    },
    "daily": {
        "summary": "Light rain off-and-on throughout the week; temperatures bottoming out at 55° on Tuesday.",
        "icon": "rain",
        "data": [
            {
                "time": 1391846400,
                "summary": "Rain and breezy throughout the day.",
                "icon": "rain",
                "sunriseTime": 1391872108,
                "sunsetTime": 1391910120,
                "moonPhase": 0.31,
                "precipIntensity": 0.0513,
                "precipIntensityMax": 0.1159,
                "precipIntensityMaxTime": 1391889600,
                "precipProbability": 0.9,
                "precipType": "rain",
                "temperatureMin": 53.63,
                "temperatureMinTime": 1391868000,
                "temperatureMax": 57.63,
                "temperatureMaxTime": 1391918400,
                "apparentTemperatureMin": 53.63,
                "apparentTemperatureMinTime": 1391868000,
                "apparentTemperatureMax": 57.63,
                "apparentTemperatureMaxTime": 1391918400,
                "dewPoint": 53.92,
                "humidity": 0.94,
                "windSpeed": 11.47,
                "windBearing": 192,
                "visibility": 5.35,
                "cloudCover": 0.98,
                "pressure": 1019.17,
                "ozone": 292.27
            },
            {
                "time": 1391932800,
                "summary": "Breezy until evening, with rain throughout the day.",
                "icon": "rain",
                "sunriseTime": 1391958446,
                "sunsetTime": 1391996587,
                "moonPhase": 0.35,
                "precipIntensity": 0.038,
                "precipIntensityMax": 0.0738,
                "precipIntensityMaxTime": 1391968800,
                "precipProbability": 1,
                "precipType": "rain",
                "temperatureMin": 55.29,
                "temperatureMinTime": 1391968800,
                "temperatureMax": 56.98,
                "temperatureMaxTime": 1391990400,
                "apparentTemperatureMin": 55.29,
                "apparentTemperatureMinTime": 1391968800,
                "apparentTemperatureMax": 56.98,
                "apparentTemperatureMaxTime": 1391990400,
                "dewPoint": 54.59,
                "humidity": 0.95,
                "windSpeed": 12.09,
                "windBearing": 217,
                "visibility": 6.94,
                "cloudCover": 1,
                "pressure": 1019.5,
                "ozone": 300.55
            },
            {
                "time": 1392019200,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1392044782,
                "sunsetTime": 1392083054,
                "moonPhase": 0.38,
                "precipIntensity": 0.0014,
                "precipIntensityMax": 0.0091,
                "precipIntensityMaxTime": 1392019200,
                "precipProbability": 0.45,
                "precipType": "rain",
                "temperatureMin": 52.66,
                "temperatureMinTime": 1392102000,
                "temperatureMax": 58.41,
                "temperatureMaxTime": 1392073200,
                "apparentTemperatureMin": 52.66,
                "apparentTemperatureMinTime": 1392102000,
                "apparentTemperatureMax": 58.41,
                "apparentTemperatureMaxTime": 1392073200,
                "dewPoint": 52.79,
                "humidity": 0.91,
                "windSpeed": 5.62,
                "windBearing": 304,
                "visibility": 10,
                "cloudCover": 0.65,
                "pressure": 1023.1,
                "ozone": 323.99
            },
            {
                "time": 1392105600,
                "summary": "Foggy in the morning.",
                "icon": "fog",
                "sunriseTime": 1392131117,
                "sunsetTime": 1392169520,
                "moonPhase": 0.41,
                "precipIntensity": 0.0003,
                "precipIntensityMax": 0.001,
                "precipIntensityMaxTime": 1392184800,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperatureMin": 49.91,
                "temperatureMinTime": 1392130800,
                "temperatureMax": 55.11,
                "temperatureMaxTime": 1392159600,
                "apparentTemperatureMin": 48.91,
                "apparentTemperatureMinTime": 1392127200,
                "apparentTemperatureMax": 55.11,
                "apparentTemperatureMaxTime": 1392159600,
                "dewPoint": 49.41,
                "humidity": 0.9,
                "windSpeed": 5.13,
                "windBearing": 278,
                "visibility": 7.23,
                "cloudCover": 0.87,
                "pressure": 1023.25,
                "ozone": 309.07
            },
            {
                "time": 1392192000,
                "summary": "Drizzle starting in the afternoon.",
                "icon": "rain",
                "sunriseTime": 1392217451,
                "sunsetTime": 1392255987,
                "moonPhase": 0.45,
                "precipIntensity": 0.0028,
                "precipIntensityMax": 0.0051,
                "precipIntensityMaxTime": 1392249600,
                "precipProbability": 0.33,
                "precipType": "rain",
                "temperatureMin": 50.72,
                "temperatureMinTime": 1392192000,
                "temperatureMax": 59.65,
                "temperatureMaxTime": 1392274800,
                "apparentTemperatureMin": 50.72,
                "apparentTemperatureMinTime": 1392192000,
                "apparentTemperatureMax": 59.65,
                "apparentTemperatureMaxTime": 1392274800,
                "dewPoint": 54.02,
                "humidity": 0.91,
                "windSpeed": 4.92,
                "windBearing": 205,
                "visibility": 10,
                "cloudCover": 0.92,
                "pressure": 1021.08,
                "ozone": 295.21
            },
            {
                "time": 1392278400,
                "summary": "Drizzle throughout the day.",
                "icon": "rain",
                "sunriseTime": 1392303784,
                "sunsetTime": 1392342453,
                "moonPhase": 0.48,
                "precipIntensity": 0.0068,
                "precipIntensityMax": 0.0078,
                "precipIntensityMaxTime": 1392303600,
                "precipProbability": 0.56,
                "precipType": "rain",
                "temperatureMin": 58.57,
                "temperatureMinTime": 1392303600,
                "temperatureMax": 62.82,
                "temperatureMaxTime": 1392332400,
                "apparentTemperatureMin": 58.57,
                "apparentTemperatureMinTime": 1392303600,
                "apparentTemperatureMax": 62.82,
                "apparentTemperatureMaxTime": 1392332400,
                "dewPoint": 58.47,
                "humidity": 0.94,
                "windSpeed": 5.13,
                "windBearing": 209,
                "cloudCover": 0.89,
                "pressure": 1019.57,
                "ozone": 288.02
            },
            {
                "time": 1392364800,
                "summary": "Overcast throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1392390115,
                "sunsetTime": 1392428918,
                "moonPhase": 0.52,
                "precipIntensity": 0.0036,
                "precipIntensityMax": 0.0053,
                "precipIntensityMaxTime": 1392364800,
                "precipProbability": 0.34,
                "precipType": "rain",
                "temperatureMin": 58.17,
                "temperatureMinTime": 1392390000,
                "temperatureMax": 62.8,
                "temperatureMaxTime": 1392418800,
                "apparentTemperatureMin": 58.17,
                "apparentTemperatureMinTime": 1392390000,
                "apparentTemperatureMax": 62.8,
                "apparentTemperatureMaxTime": 1392418800,
                "dewPoint": 57.69,
                "humidity": 0.91,
                "windSpeed": 4.37,
                "windBearing": 214,
                "cloudCover": 0.98,
                "pressure": 1018,
                "ozone": 271.7
            },
            {
                "time": 1392451200,
                "summary": "Breezy until afternoon, with light rain until evening.",
                "icon": "rain",
                "sunriseTime": 1392476445,
                "sunsetTime": 1392515384,
                "moonPhase": 0.55,
                "precipIntensity": 0.0135,
                "precipIntensityMax": 0.0428,
                "precipIntensityMaxTime": 1392505200,
                "precipProbability": 0.83,
                "precipType": "rain",
                "temperatureMin": 53.88,
                "temperatureMinTime": 1392534000,
                "temperatureMax": 59.72,
                "temperatureMaxTime": 1392451200,
                "apparentTemperatureMin": 53.88,
                "apparentTemperatureMinTime": 1392534000,
                "apparentTemperatureMax": 59.72,
                "apparentTemperatureMaxTime": 1392451200,
                "dewPoint": 55.94,
                "humidity": 0.92,
                "windSpeed": 7.83,
                "windBearing": 205,
                "cloudCover": 0.92,
                "pressure": 1017.21,
                "ozone": 293.98
            }
        ]
    },
    "flags": {
        "sources": [
            "nwspa",
            "isd",
            "fnmoc",
            "sref",
            "rtma",
            "rap",
            "nam",
            "cmc",
            "gfs",
            "madis",
            "lamp",
            "darksky",
            "nearest-precip"
        ],
        "isd-stations": [
            "724943-99999",
            "745039-99999",
            "745065-99999",
            "994016-99999",
            "999999-23272"
        ],
        "madis-stations": [
            "D8582",
            "D9724",
            "FTPC1",
            "GGBC1",
            "PXOC1"
        ],
        "lamp-stations": [
            "KCCR",
            "KHWD",
            "KOAK",
            "KSFO",
            "KSQL"
        ],
        "darksky-stations": [
            "KMUX"
        ],
        "units": "us"
    }
}
 */